# Generated by Django 2.2.12 on 2020-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_uuid', models.UUIDField()),
                ('url', models.URLField()),
            ],
        ),
    ]
