# Generated by Django 2.2.12 on 2020-05-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0004_auto_20200501_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlwatchresult',
            name='diff',
            field=models.TextField(blank=True, null=True),
        ),
    ]
